### ISSUE TITLE
Some characters are escaped when pretty printing

### ISSUE THREAD

**Issue by rhamzeh** [openfga/cli#188]
Notice below how `<` is being escaped into `\u003c` below

`sample-stores git:(main) ✗ fga model transform --file model.fga`
```json 
{
  "schema_version":"1.1",
  "type_definitions": [
    {
      "type":"user"
    },
    {
      "metadata": {
        "relations": {
          "viewer": {
            "directly_related_user_types": [
              {
                "condition":"conditionX",
                "type":"user"
              }
            ]
          }
        }
      },
      "relations": {
        "viewer": {
          "this": {}
        }
      },
      "type":"document"
    }
  ],
  "conditions": {
    "conditionX": {
      "expression":"\n  x \u003c 100\n",
      "name":"conditionX",
      "parameters": {
        "x": {
          "type_name":"TYPE_NAME_INT"
        }
      }
    }
  }
}
```

`sample-stores git:(main) ✗ fga model transform --file model.fga | jq`
```json
{
  "schema_version": "1.1",
  "type_definitions": [
    {
      "type": "user"
    },
    {
      "metadata": {
        "relations": {
          "viewer": {
            "directly_related_user_types": [
              {
                "condition": "conditionX",
                "type": "user"
              }
            ]
          }
        }
      },
      "relations": {
        "viewer": {
          "this": {}
        }
      },
      "type": "document"
    }
  ],
  "conditions": {
    "conditionX": {
      "expression": "\n  x < 100\n",
      "name": "conditionX",
      "parameters": {
        "x": {
          "type_name": "TYPE_NAME_INT"
        }
      }
    }
  }
}
```

**Comment by ewanharris** [comment]
Writing down some findings from looking into this.

The escaping occurs in all 3 output types (non-TTY, TTY with colour, TTY without colour), it's just that `jq` unescapes the characters so it appears like it's limited. The issue is occurring because of custom `MarshalJSON` func in the `Condition` struct calling `json.Marshal` which will escape HTML characters in the string, [this Go playground](https://go.dev/play/p/bAqTPs6oTZY) demonstrates the issue.

There's 2 potential fixes here in different places:
1. Change the Go SDK to use a `json.Encoder` instead of using `json.Marshal`, this allows us to call `SetEscapeHTML(false)` and disable the HTML escaping. There are some complexities around doing this correctly in the sdk-generator, and also potentially a security concern too. 
3. We decide that unescaping is the job of the consumer of the SDK and handle it within the CLI, `nwidger/jsoncolor` is able to handle unescaping the HTML for us so we can change the printing logic to use that in all scenarios. This is the "easier" fix but would leave the onus on developers consuming the Go SDK to ensure the unescaping happens (although most JSON parsers will actually handle this I believe)
