### ISSUE TITLE
Import tuples from a csv

### ISSUE THREAD

**Issue by le-yams** [openfga/cli#206]
Hello,

We have a private tool to massively import tuples for a given relation from a csv file.

Our use case: 
When migrating permissions from a legacy system to openfga, we need to import all existing permissions as openfga relations. Legacy permissions are exported from the system database as a csv file.
The csv is expected to have 2 columns, the first being the user id and the second the object id. The command has mandatory options to specify the user type, the relation and the object type (In addition to common target server/auth/store related options).

Example
```
cli import-tuples <common options> --user-type user --relation administrator --object-type organization organizations_administrators.csv
```

The command batches the tuples import  (batch size is configurable with an option). 
All failling batches imports are written to a "failed" csv having the same structure as the input one (so it can be re-used as input itself).

Is it something you would be interested in?

Regards,
Yann

**Comment by rhamzeh** [comment]
Hi @le-yams!

Yeah definitely, we wanted to add a csv import at sonepoint. however instead of introducing a new command, we can add that to the write itself (fga tuple write)

The write already accepts a yaml or json file.

We can have it accept a csv file too, in case the input is a csv it does some parsing and massaging of the data, but the import proceeds as normal.

For the options, what were you thinking?

By default I think expecting:
`user_type,user_id,user_relation,relation,object_type,object_id` would be nice.

We can add an option of `--csv-header` that accepts a string to specify order too.

I don't want to add too many options, but if you have some that may be useful we can see about them.

What do you think?

cc @aaguiarz

**Comment by aaguiarz** [comment]
I also like the idea of defining a default for some tuple values (e.g. user_type, relation, object_type). They would be valuable for json/yaml import too.

Generating a file with failed ones can be practical tool.

**Comment by le-yams** [comment]
Hey @rhamzeh , @sergiught ,

Sorry for the late reply, the support you've added is great 👍 and more flexible than my initial proposal so big shout-out to you ❤️. 

> Update: Reopening in order for us to explore in the future not forcing users to define redundant fields within multiple rows if only a subset of headers need to change.

Would it be for csv imports only or  also for json and yaml?

> Generating a file with failed ones can be practical tool.

Would you like that I open a dedicated issue (as it probably isn't specific to csv format)?

**Comment by rhamzeh** [comment]
> Would it be for csv imports only or also for json and yaml?

This would be csv specific as in yaml and json, you can not set those fields for the tuples that don't need them.

For CSV, it's a different matter.

As an enhancement on this, we want to:
- allow users not to set header fields they don't need (e.g. if you are not using conditions, you should be able to not set the `condition_name` and `condition_context` headers in the CSV)
- allow users to define default types, e.g. `import --default-user-type=employee` in which we will assume the user_type field to be `employee` if not set
