### ISSUE TITLE
`go install` could not find cli

### ISSUE THREAD

**Issue by own2pwn** [openfga/cli#261]
```
sudo docker run --rm -it golang
go install github.com/openfga/cli/cmd/fga@latest
go: github.com/openfga/cli/cmd/fga@latest: module github.com/openfga/cli@latest found (v0.2.5), but does not contain package github.com/openfga/cli/cmd/fga
```

**Comment by ewanharris** [comment]
Thanks for the issue @own2pwn, we restructured the CLI slightly (#242) between the `v0.2.5` and `v0.2.6` releases so I think at the time when this issue was filed the install command wasn't correct for the released version.

`go install github.com/openfga/cli/cmd/fga@latest` now works as we released `v0.2.6` last week with those changes. If you need to install `v0.2.5` or older then it has to be `go install github.com/openfga/cli@<version>`
